@startuml
'https://plantuml.com/class-diagram

class App
class NameList

App o-- NameList

class NameList {
ArrayList<String> nameList
setNameList()
getNameList()
sortNames()
readFile()
}

class App {
String path
String outputPath
NameList names
createFile()
writeFile()
}

@enduml